### ISSUE TITLE
Typo in linked Medium article: “swift” -> “switch”

### ISSUE THREAD

**Issue by pfurbacher** [romanzuch/CustomViewRouter#1]
In your [Medium article](https://roman-ios.medium.com/create-your-custom-view-router-with-swiftui-be7f938d9c33) you wrote 

`Instead of putting content directly into your body, you provide a swift that shows content based on the variable created above.`

I think you meant `switch` not `swift`.

**Comment by romanzuch** [comment]
Thank you very much. Just updated it.
